### PR TITLE
try copy

### PR DESCRIPTION
**Pull request by Carreau**
Trying to work out how to duplicate things (forget about things in `drive_utils.js` for now) 
I get a 500 from server, and don't understand why...

Am I doing  smth dumb ?

### CODE REVIEW

**Comment by KesterTong** [comment]
I don't understand either.  I tried playing around for a bit, but no matter what I do I get the same 500 error.  This was the code that I thought was most likely to work (but didn't):
```
var body = {
    'title': 'Copy of ' + resource['title'],
    'parents': [{
        'id': resource['parents'][0]['id']
    }]
};
var request = gapi.client.drive.files.copy({
    'fileId': resource['id'],
    'resource': body
});
```

**Comment by KesterTong** [comment]
Ok the problem is that it doesn't work with drive.file scope.  I checked this by changing the scope to drive, and then in worked.  I've filed a bug with the Drive team.

**Comment by KesterTong** [comment]
btw this should fail if we don't have access to the file yet.  I think we need some "preflight" logic that tries to download 1 byte of the file, like you suggested earlier.

**Comment by Carreau** [comment]
Closing to keep the list of open PR short. I can reopen later.

**Pull request closed without merging**
