### PR TITLE
fix deletion

### PR DESCRIPTION
**Pull request by Carreau**
Ok, took me the day to figure out why. 
And I really wanted to punch Javascript in the face may times.

### CODE REVIEW

**Comment by KesterTong** [comment]
Thanks for the fix.  Now that we have fixed all bugs, do you think you could update pypi and make an announcement that it is ready for prime time? @ellisonbg Are there other places/ways we could announce this?

**Comment by Carreau** [comment]
> Now that we have fixed all bugs

Hahaha, sure there are still some :-) 

I'll do that on twitter, jupyter ML, and IPython one. 
I think the rest will follow.

**Comment by KesterTong** [comment]
great, thanks

**Comment by ellisonbg** [comment]
Congrats! Well done! All of us will re tweets when it comes out.

**Pull request merged**
