### PR TITLE
Live edition in editor.

### PR DESCRIPTION
**Pull request by Carreau**
For @KesterTong to be used with https://github.com/ipython/ipython/pull/7987

Do not merge.

### CODE REVIEW

**Comment by KesterTong** [comment]
thanks.  This doesn't work for me, seems like you need to add

```
if (root.get('text') == null) {
  root.set('text', model.createString());
}
```
to drive_utils.js

**Comment by KesterTong** [comment]
(it does work when I add this)

**Comment by Carreau** [comment]
Oh, yes, I did this by hand on a file. 
Right now we had internet down in Berkeley and GAPI still does not get through. 
I'll fix things up once it works again.

**Comment by Carreau** [comment]
I fixed teh creation of new files yesterday.

**Pull request closed without merging**
