### PR TITLE
insert user avatar in header

### PR DESCRIPTION
**Pull request by Carreau**
At least this give a hint that they are on google drive

capture d ecran 2014-12-19 a 13 59 47

(object not defined is unrelated to this)

### CODE REVIEW

**Comment by Carreau** [comment]
Should be updated and  rebased.

**Comment by KesterTong** [comment]
Thanks for this, avatar makes a big difference

**Comment by Carreau** [comment]
Yeah, I'll later make it the menu to log-out and other stuff. 

right now i'm struggling with metadata to know wether or not in the tree view we'll be able to 
access the file or not. Though I seem to get `edittable=true` always, even if the download url will fail with 404. 

any idea how to do it ?

**Comment by KesterTong** [comment]
The only way is to actually try to download the file.  If it fails at that point (when it has the metadata but downloading the downloadUrl fails with 404 or maybe 401), then you can be sure that the reason is the drive.file scope.

**Comment by Carreau** [comment]
> The only way is to actually try to download the file. If it fails at that point (when it has the metadata but downloading the downloadUrl fails with 404 or maybe 401), then you can be sure that the reason is the drive.file scope.

That's a bit annoying.

**Comment by KesterTong** [comment]
And in that case explain to the user the issue.  I think one solution is create a blank notebook with this app, then upload a new version in the Drive website, with the actual file you want.

**Comment by KesterTong** [comment]
But there is nothing in the IPython UI to indicate that a file can't be downloaded anyway.  So warning the user when they actually try to open the file should be ok right?

**Comment by Carreau** [comment]
Yep I guess, I'll try. 
We might also try to get only the first byte and grey things in the tree.

**Comment by KesterTong** [comment]
Thanks to Google folks, there is a workaround:  If we can get an OAuth token with just the Drive.File scope, and make the same calls for listing all files with that token, then that call will only return the files that can be accessed with Drive.File access.

I'm just looking into how to obtain this token and use it.  It might not be properly supported in the JavaScript API (gapi.*) but we can directly make REST calls to Google servers, and then it should be possible.

**Comment by Carreau** [comment]
Cool. Are there any plan to update drive api to allow something similar without this "hack" ?

**Comment by KesterTong** [comment]
Not as far as I'm aware.  Also it might not be so easy - because tokens are cached in the browser, it might be hard to "forget" the original token which has both scopes.

**Pull request merged**
