### PR TITLE
Adding logic to handle empty data.conf.

### PR DESCRIPTION
**Pull request by ellisonbg**
Work done by @Carreau ....

### CODE REVIEW

**Comment by Carreau** [comment]
Live merging from Strata.

**Comment by KesterTong** [comment]
Thanks, was this discovered during a demo?

**Comment by ellisonbg** [comment]
No I just tried to install and run it and we found this...

On Fri, Feb 20, 2015 at 3:04 PM, Kester Tong <notifications@github.com>
wrote:

> Thanks, was this discovered during a demo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter-drive/pull/80#issuecomment-75335907>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by KesterTong** [comment]
cool, hope it works now :-)

**Pull request merged**
