### PR TITLE
start converting to typscript

### PR DESCRIPTION
**Pull request by Carreau**
Mostly a test for now.

### CODE REVIEW

**Comment by minrk** [comment]
Cool. How are you liking it at this point?

**Comment by Carreau** [comment]
Meh. I forced myself to do is as I haven't touched typescript in a while. 
I mostly wanted to see how easy it was to convert a single file without dependencies to still work with some other pure-js module. 

It's quite easy (as you can see) for single things. There seem to be extra boiler plate, like all exported function should be in a class AFAIU, I'll try to do better though.

**Comment by Carreau** [comment]
fiddling around it is possible to remove the class, and thus revert the methods declaration pure function, which make it nicer.

**Comment by Carreau** [comment]
Yeahhh it works, one more file as TypeScript. I commited the various .d.ts and other file to have it work our of the box!

**Comment by Carreau** [comment]
Ok, roughly works, need testing to be sure all the things are exported correctly.

**Comment by Carreau** [comment]
Ok, I've been playing with that for a couple of days, merging to get some more testing

**Pull request merged**
