### PR TITLE
DOC: README: Add deprecation notice

### PR DESCRIPTION
**Pull request by westurner**

### CODE REVIEW

**Comment by westurner** [comment]
Looks like the build is only failing due to the py3.3 installer not being downloadable from https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.3.tar.bz2 on every build: https://travis-ci.org/github/jupyter/jupyter-drive/jobs/667322656

**Comment by westurner** [comment]
@Carreau Looks like the build is only failing due to the py3.3 installer not being downloadable from https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.3.tar.bz2 on every build: https://travis-ci.org/github/jupyter/jupyter-drive/jobs/667322656

**Comment by Carreau** [comment]
Ah yes. If that's just that I'll merge later from my computer, and remove testing on 3.3 (and 3.4). Thanks for doing this !

**Comment by Carreau** [comment]
I think that's good as is. We can archive if we get too much activity.

**Pull request merged**
