### PR TITLE
Fix Google API timeout in long-lived notebooks

### PR DESCRIPTION
**Pull request by rjw57**
The Google Auth Token returned by the OAuth 2.0 dance has an inbuilt expiry of, by default, 3600 seconds or 1 hour. After this time the notebook will fail to autosave and the notebook list view will no longer update.

The failure to save is shown in the UI by a relatively easy to miss notification and this resulted in loss of work for me after I left a notebook open while I went to lunch.

The Google-blessed approach[1] is to refresh the auth token before expiry. This pull request implements this approach in 3c42a21.

It also implements a defensive measure in 3d88257 to address the failure mode where setTimeout doesn't fire within 45 minutes of wall-clock time. (Such as, for example, when a laptop is suspended.) This measure is to attempt a re-auth on the *first* 401 encountered when an API request is executed. Subsequent 401s are allowed to propagate back to the caller since they are then assumed to be "true" permission denied responses. (This approach mirrors other Google sample code but is not terribly elegant.)

Finally, 6c5b0c8 is a re-build of all the JavaScript from the modified TypeScript. Since TypeScript appears to have changed its whitespace handling since the last build, it touches all the JavaScript source (sorry) and is broken out into a separate commit for easier review.

[1] https://developers.google.com/api-client-library/javascript/help/faq

### CODE REVIEW

**Comment by Carreau** [comment]
+1, 

Should we think of removing the `.js` files as they are generated ?

**Comment by rjw57** [comment]
> Should we think of removing the .js files as they are generated ?

We could do but generating them would need to become part of the install step. (I don't *think* they're generated automatically on demand?) At the moment it's nice that all one needs to do to get Jupyter-drive working is pip install it.

**Comment by rjw57** [comment]
Addendum: and I don't think putting an ``npm install && gulp`` step as part of ``setup.py`` is wise. It feels like a magic step too far.

**Comment by Carreau** [comment]
No but, if you bublish as wheel, you can generate the JS files at build time. So only install from git (or tarball) requires building. Plus the wheel would be universal, so woudl work on linux.

**Comment by rjw57** [comment]
> Plus the wheel would be universal, so woudl work on linux.

But it already works on Linux(!) (Or, at least, pip installing worked for me.)

But, yes, making it a wheel would work well in this case. I've no feeling for how complex adding the magic would be. If it's feasible, maybe opening a new issue to discuss it/request input?

**Comment by Carreau** [comment]
OK, let's merge and see that later.

**Pull request merged**
